### ISSUE TITLE
Convert array declaration to Java-Style from C-Style

### ISSUE THREAD

**Issue by adit19shah** [MSTC-DA-IICT/Sun-Chokdi#10]
**Describe the bug**
The array ```winPositions``` defined to use the winning positions is currently defined in C-style format.

**Expected behavior**
The array ```winPositions``` should be converted to Java-Style array.

**Where to start ?**
https://github.com/MSTC-DA-IICT/Sun-Chokdi/blob/0b505d89e5e95d7aab39efeef1771cbffa603d85/app/src/main/java/com/adit/tictactoe/MainActivity.java#L20
Changing ```int winPositions[][]``` to ```int[][] winPositions ``` &nbsp; would convert the array declaration to Java-Style.

**Comment by adit19shah** [comment]
@kfkonrad and @RiyaBhandari-2811 please go through our [contributing guidelines](https://github.com/MSTC-DA-IICT/Sun-Chokdi#contributing) mentioned in the Readme. You need to first comment here, then we'll assign the issue to you. You can make PR for an issue only after you are assigned that issue.

**Comment by kfkonrad** [comment]
I'd like to work on this issue, can you assign me please?

**Comment by adit19shah** [comment]
> I'd like to work on this issue, can you assign me please?

Assigned to you @kfkonrad , Thanks.

**Comment by kfkonrad** [comment]
See https://github.com/MSTC-DA-IICT/Sun-Chokdi/pull/11 for a PR
