### ISSUE TITLE
Optimize for loop with Arrays.fill() method available in Java

### ISSUE THREAD

**Issue by adit19shah** [MSTC-DA-IICT/Sun-Chokdi#12]
**Describe the bug**
In the current code, we are using a for loop to reset the board for new game.

**Expected behavior**
The for loop can be avoided by using Java's Arrays.fill() method.

**Where to start ?**
https://github.com/MSTC-DA-IICT/Sun-Chokdi/blob/0b505d89e5e95d7aab39efeef1771cbffa603d85/app/src/main/java/com/adit/tictactoe/MainActivity.java#L84-L86

Replace this for loop with a single call to ```Arrays.fill()``` method.
The documentation about ```Arrays.fill()``` method can be found [here](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#:~:text=range%20of%20the%20specified%20array%20of%20floats.-,static%20void,value%20to%20each%20element%20of%20the%20specified%20array%20of%20ints.,-static%20void).

**Comment by Dhi13man** [comment]
Will do. Please assign. :)

**Comment by Alankruthisaieni** [comment]
I'd like to work on this issue.

**Comment by adit19shah** [comment]
> Will do. Please assign. :)

Assigned to you @Dhi13man , Thanks.

**Comment by Dhi13man** [comment]
It's done. Please verify. :)
