### ISSUE TITLE
Display a Stikethrough ( x̶x̶x̶  ,  ̶o̶o̶o̶  ) through the winning line at the end of the game.

### ISSUE THREAD

**Issue by sarthakhp** [MSTC-DA-IICT/Sun-Chokdi#2]
**Is your feature request related to a problem? Please describe.**
App does not show the user that which line was the winning one at the end of the game.

**Describe the solution you'd like**
App should display a line passing through the three symbols the made the player win the game at the end.

How the solution will look after implementation:
![image](https://user-images.githubusercontent.com/58687634/135610839-827273bf-9dc6-429f-9e13-88a92c8d4197.png)

**Comment by MeetSable** [comment]
I'd like to work on this issue.

**Comment by sarthakhp** [comment]
@MeetSable Assigned
