### ISSUE TITLE
Make Different Activity for beginning the game

### ISSUE THREAD

**Issue by sarthakhp** [MSTC-DA-IICT/Sun-Chokdi#22]
**The problem.**
Currently there's a window on the same activity that begins the game, but this restricts us to add more features and a menu.

**Solution**
Make a new activity that is shown when the app is started and add a button that sends us to the main game activity.

**Comment by advait2205** [comment]
@sarthakhp I have solved this problem in PR #20. Where i Have added a new activity to take us to either of the game modes.
 The PR has been accepted and merged so, you can close this issue
