### ISSUE TITLE
Single Player option by playing against Computer

### ISSUE THREAD

**Issue by sarthakhp** [MSTC-DA-IICT/Sun-Chokdi#4]
**Is your feature request related to a problem? Please describe.**
Two players are needed to play the game. No option for computer as an opponent.

**Describe the solution you'd like**
Add algorithm to let computer decide and make moves and change the UI programatically. 
Minimax algorithm can be used. 
Heres an explaination for the algorithm: [https://www.youtube.com/watch?v=trKjYdBASyQ&ab_channel=TheCodingTrain](url)

**Comment by advait2205** [comment]
I'd like to work on this issue

**Comment by adit19shah** [comment]
> I'd like to work on this issue

Assigned, Thanks.

**Comment by advait2205** [comment]
Required Pull Request Made in PR #20  --- play against computer added. Look PR #20 for working proof

**Comment by advait2205** [comment]
Hello Guys! I have added PR #20 Please look into that
