### ISSUE TITLE
Absence of Reset button after the game ends

### ISSUE THREAD

**Issue by vidhibadrakiya** [MSTC-DA-IICT/Sun-Chokdi#5]
**Is your feature request related to a problem? Please describe.**
Currently, after completion of game, we need to randomly tap on some cell to reset the board. This does not create a good user experience since a first time user won't know how to reset board after the game ends.

**Describe the solution you'd like**
After finishing game there should be a reset button to reset the board for playing again.

**Comment by advait2205** [comment]
I'd like to work on this issue!

**Comment by adit19shah** [comment]
Thanks @advait2205, assigned to you. Please make sure that you make PRs for each issue individually if you are working on multiple issues.
