### ISSUE TITLE
To choose starting player as X or O  

### ISSUE THREAD

**Issue by vidhibadrakiya** [MSTC-DA-IICT/Sun-Chokdi#6]
**Is your feature request related to a problem? Please describe.**
Currently, the game does not give any option(s) and directly starts with 'X' as the first token.

**Describe the solution you'd like**
There should be an option to choose the first token as 'X' or 'O'.

**Comment by advait2205** [comment]
I'd like to work on this issue

**Comment by vidhibadrakiya** [comment]
Assigned to you.

**Comment by advait2205** [comment]
Thanks! PR done #16
