### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by vidhibadrakiya** [MSTC-DA-IICT/Sun-Chokdi#7]
**Is your feature request related to a problem? Please describe.**
When app starts it directly leads to the game no splash screen.

**Describe the solution you'd like**
Splash screen as logo and name of the app . 

**Example: Splash Screen in Amazon App**
![image](https://user-images.githubusercontent.com/58687634/135611078-0598be68-bd08-49b7-ab65-bdb17cbbbebe.png)

**Comment by advait2205** [comment]
I'd like to work on this issue.

**Comment by adit19shah** [comment]
@advait2205 you can first design the logo as a part of #8 and then work on this issue. Will assign it to you once PR for #8 is merged.

**Comment by advait2205** [comment]
So, now can i work on this issue ?

**Comment by adit19shah** [comment]
> So, now can i work on this issue ? 
> 

Yes, assigned to you @advait2205 .

**Comment by advait2205** [comment]
I have made the PR #15
