### ISSUE TITLE
Design an attractive icon/logo for this app

### ISSUE THREAD

**Issue by adit19shah** [MSTC-DA-IICT/Sun-Chokdi#8]
**Is your feature request related to a problem? Please describe.**
The app currently has the default Android Studio image as its icon. That icon isn't describing what the app is about.

**Describe the solution you'd like**
There should be an appropriate icon that symbolizes something about the app. In this case, it could be something related to Tic-Tac-Toe game.

**Comment by advait2205** [comment]
I'd like to work on this issue

**Comment by adit19shah** [comment]
@advait2205 assigned. Thanks.

**Comment by advait2205** [comment]
Hello there!  Thanks for assigning me the issue. I have generated a PR please look into it! Thank You!

**Comment by SiddyDevelops** [comment]
Hello! If this issue is still open can I work on it?

**Comment by adit19shah** [comment]
> Hello! If this issue is still open can I work on it?

@SiddyDevelops this issue is already fixed by @advait2205, you can try commenting on other open issues.
